### ISSUE TITLE
Issues installing with the new qiime2 version 2-2021.8

### ISSUE THREAD

**Issue by shreyaskumbhare** [bioinf-mcb/q2-health-index#15]
Hi @wwydmanski I am interested in using this plugin. However I am facing issues with installing it with the new version of qiime2-2021.8. Is this plugin compatible with this version? Or any plans to make it compatible?

Thanks!

**Comment by PawelSzczerbiak** [comment]
Hi @shreyaskumbhare Sorry for late reply. I've just checked the plugin installation on my macOS (version `11.2.3`) with `qiime2-2021.8` and everything works fine. Could you provide a little bit more details what went wrong?

**Comment by shreyaskumbhare** [comment]
Hi, @PawelSzczerbiak and @tkosciol sorry for the delay in responding! I think there were a few issues with my qiime installations. It's working fine with the qiime2-2021.8. Thanks!
