### ISSUE TITLE
Logical flaw in `calculate_gmhi` implementation

### ISSUE THREAD

**Issue by crusher083** [bioinf-mcb/q2-health-index#9]
Parameters `MH_prime` and `MN_prime` should come as variables calculated on a training dataset, therefore they should be provided to `calculate_gmhi` as parameters, not calculated every time function is executed.
This removes the need for metadata input to the function and allows for index calculation solely on gut microbiome data.

**Comment by PawelSzczerbiak** [comment]
Thanks for pointing this out. We actually need two separate actions for training and computing GMHI. We will work on that soon.
